apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-deployment
  labels:
    app: whiteboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whiteboard
  template:
    metadata:
      labels:
        app: whiteboard
    spec:
      containers:
        - name: whiteboard
          image: whiteboard:v1
          ports:
            - containerPort: 10001
          env:
            - name: redis.host
              valueFrom:
                configMapKeyRef:
                  name: redis-configmap
                  key: redis_url
---
apiVersion: v1
kind: Service
metadata:
  name: whiteboard-service
spec:
  selector:
    app: whiteboard
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001
      nodePort: 30000